export default {
  "id": "base64-tool",
  "name": "Base64 Tool",
  "description": "Encode and decode text to/from Base64 format.",
  "author": "Infinition",
  "authorUrl": "https://github.com/infinition",
  "cols": 8,
  "rows": 13,
  "html": "<div class=\"widget-card\">\n  <h4 class=\"widget-title\">🔐 Base64 Tool</h4>\n  \n  <div class=\"input-group\">\n    <label>Raw Text</label>\n    <textarea id=\"raw-text\" placeholder=\"Enter text...\" oninput=\"encode()\" onblur=\"save()\"></textarea>\n  </div>\n\n  <div class=\"separator\">↕</div>\n\n  <div class=\"input-group\">\n    <label>Base64</label>\n    <textarea id=\"b64-text\" placeholder=\"RW50ZXIgdGV4dC4uLg==\" oninput=\"decode()\" onblur=\"save()\"></textarea>\n  </div>\n\n  <div class=\"actions\">\n    <button onclick=\"copy('b64-text')\">Copy B64</button>\n    <button onclick=\"copy('raw-text')\">Copy Raw</button>\n    <button class=\"btn-clear\" onclick=\"clearFields()\">Clear</button>\n  </div>\n</div>",
  "css": ":host { display: block; width: 100%; height: 100%; min-width: 0; min-height: 0; overflow: hidden; box-sizing: border-box; font-family: var(--font-interface); }\n.widget-card {\n    width: 100%;\n    height: 100%;\n    min-width: 0;\n    min-height: 0;\n    display: flex;\n    flex-direction: column;\n    overflow: hidden;\n    background: var(--background-secondary);\n    color: var(--text-normal);\n    border-radius: 12px;\n    padding: 1.5rem;\n    box-shadow: var(--shadow-s);\n    border: 1px solid var(--background-modifier-border);\n    text-align: center;\n    box-sizing: border-box;\n}\n.widget-title { margin: 0 0 1.5rem 0; font-size: 0.9rem; font-weight: 800; color: var(--interactive-accent); text-transform: uppercase; letter-spacing: 2px; }\n\n.input-group { text-align: left; }\n.input-group label { display: block; font-size: 0.65rem; font-weight: 700; color: var(--interactive-accent); margin-bottom: 4px; text-transform: uppercase; }\n.input-group textarea {\n    width: 100%;\n    max-width: 100%;\n    min-width: 0;\n    height: 80px;\n    min-height: 60px;\n    background: var(--background-primary);\n    border: 1px solid var(--background-modifier-border);\n    color: var(--text-normal);\n    caret-color: var(--interactive-accent);\n    border-radius: 4px;\n    padding: 10px;\n    font-size: 0.85rem;\n    outline: none;\n    resize: vertical;\n    font-family: var(--font-monospace);\n    box-sizing: border-box;\n}\n.input-group textarea:focus {\n    border-color: var(--interactive-accent);\n}\n\n.separator { margin: 8px 0; font-size: 1.2rem; color: var(--text-muted); }\n\n.actions { display: flex; gap: 8px; margin-top: 1rem; }\n.actions button {\n    flex: 1;\n    background: var(--interactive-accent);\n    color: var(--text-on-accent);\n    border: none;\n    padding: 8px;\n    border-radius: 4px;\n    font-weight: 600;\n    font-size: 0.75rem;\n    cursor: pointer;\n    transition: opacity 0.2s;\n}\n.actions button:hover { opacity: 0.8; }\n.actions .btn-clear {\n    background: var(--background-modifier-error);\n    color: white;\n}",
  "js": "const { root, saveState, getState } = api;\n\nfunction encode() {\n    const raw = root.getElementById('raw-text').value;\n    try {\n        const b64 = btoa(unescape(encodeURIComponent(raw)));\n        root.getElementById('b64-text').value = b64;\n    } catch(e) { \n        root.getElementById('b64-text').value = '';\n    }\n}\n\nfunction decode() {\n    const b64 = root.getElementById('b64-text').value;\n    try {\n        const raw = decodeURIComponent(escape(atob(b64)));\n        root.getElementById('raw-text').value = raw;\n    } catch(e) { \n        root.getElementById('raw-text').value = '';\n    }\n}\n\nfunction save() {\n    const raw = root.getElementById('raw-text').value;\n    saveState(raw);\n}\n\nfunction clearFields() {\n    root.getElementById('raw-text').value = '';\n    root.getElementById('b64-text').value = '';\n    saveState('');\n}\n\nfunction copy(id) {\n    const el = root.getElementById(id);\n    if (navigator.clipboard && navigator.clipboard.writeText) {\n        navigator.clipboard.writeText(el.value);\n    } else {\n        el.select();\n        document.execCommand('copy');\n    }\n}\n\nasync function init() {\n    const saved = await getState();\n    if (saved) {\n        root.getElementById('raw-text').value = saved;\n        const b64 = btoa(unescape(encodeURIComponent(saved)));\n        root.getElementById('b64-text').value = b64;\n    }\n}\n\ninit();",
  "tags": [
    "tools",
    "development",
    "encoding"
  ],
  "lastModifiedDate": 1769807038493,
  "createdDate": 1769807038493
};
