export default {
  "id": "char-counter",
  "name": "Character Counter",
  "description": "Count characters, words, and lines in your text.",
  "author": "Infinition",
  "authorUrl": "https://github.com/infinition",
  "html": "<div class=\"char-container\">\n  <h4 class=\"widget-title\">📝 Text Stats</h4>\n  \n  <textarea id=\"text-input\" placeholder=\"Type or paste text here...\" oninput=\"updateStats()\" onblur=\"save()\"></textarea>\n\n  <div class=\"stats-grid\">\n    <div class=\"stat-box\">\n      <span id=\"char-count\">0</span>\n      <label>Chars</label>\n    </div>\n    <div class=\"stat-box\">\n      <span id=\"word-count\">0</span>\n      <label>Words</label>\n    </div>\n    <div class=\"stat-box\">\n      <span id=\"line-count\">0</span>\n      <label>Lines</label>\n    </div>\n    <div class=\"stat-box\">\n      <span id=\"read-time\">0s</span>\n      <label>Read Time</label>\n    </div>\n  </div>\n</div>",
  "css": ":host {\n    display: flex;\n    flex-direction: column;\n    width: 100%;\n    height: 100%;\n    min-width: 0;\n    min-height: 0;\n    overflow: hidden;\n    box-sizing: border-box;\n    font-family: var(--font-interface);\n}\n* { box-sizing: border-box; }\n\n.char-container {\n    background: var(--background-secondary);\n    border: 1px solid var(--background-modifier-border);\n    border-radius: 16px;\n    padding: 1.25rem;\n    color: var(--text-normal);\n    box-shadow: var(--shadow-s);\n    width: 100%;\n    height: 100%;\n    min-width: 0;\n    min-height: 0;\n    overflow: hidden;\n    display: flex;\n    flex-direction: column;\n}\n\n.widget-title {\n    margin: 0 0 1.25rem 0;\n    font-size: 0.85rem;\n    font-weight: 600;\n    color: var(--text-muted);\n    text-transform: uppercase;\n    letter-spacing: 0.05em;\n    text-align: center;\n    flex-shrink: 0;\n}\n\ntextarea {\n    width: 100%;\n    flex: 1;\n    min-height: 80px;\n    background: var(--background-primary);\n    border: 1px solid var(--background-modifier-border);\n    color: var(--text-normal);\n    border-radius: 12px;\n    padding: 12px;\n    font-size: 0.9rem;\n    outline: none;\n    resize: none;\n    margin-bottom: 1.25rem;\n    font-family: var(--font-monospace);\n    transition: border-color 0.2s;\n    display: block;\n    box-sizing: border-box;\n}\n\ntextarea:focus {\n    border-color: var(--interactive-accent);\n}\n\n.stats-grid {\n    display: grid;\n    grid-template-columns: repeat(4, 1fr);\n    gap: 10px;\n}\n\n.stat-box {\n    background: var(--background-primary);\n    padding: 12px 4px;\n    border-radius: 10px;\n    border: 1px solid var(--background-modifier-border);\n    text-align: center;\n    display: flex;\n    flex-direction: column;\n    gap: 4px;\n}\n\n.stat-box span {\n    display: block;\n    font-size: 1.1rem;\n    font-weight: 700;\n    color: var(--interactive-accent);\n}\n\n.stat-box label {\n    font-size: 0.65rem;\n    font-weight: 600;\n    text-transform: uppercase;\n    color: var(--text-muted);\n    letter-spacing: 0.02em;\n}",
  "js": "const { root, saveState, getState } = api;\n\nfunction updateStats() {\n    const text = root.getElementById('text-input').value;\n    \n    const chars = text.length;\n    const words = text.trim() ? text.trim().split(/\\s+/).length : 0;\n    const lines = text ? text.split('\\n').length : 0;\n    \n    // Reading time calculation (200 words per minute)\n    const readTimeSec = Math.round((words / 200) * 60);\n    let readTimeStr = \"0s\";\n    \n    if (words > 0) {\n        if (readTimeSec < 60) {\n            readTimeStr = Math.max(1, readTimeSec) + \"s\";\n        } else {\n            const mins = Math.floor(readTimeSec / 60);\n            const secs = readTimeSec % 60;\n            readTimeStr = secs > 0 ? `${mins}m ${secs}s` : `${mins}m`;\n        }\n    }\n\n    root.getElementById('char-count').innerText = chars.toLocaleString();\n    root.getElementById('word-count').innerText = words.toLocaleString();\n    root.getElementById('line-count').innerText = lines.toLocaleString();\n    root.getElementById('read-time').innerText = readTimeStr;\n}\n\nfunction save() {\n    const text = root.getElementById('text-input').value;\n    saveState(text);\n}\n\nasync function init() {\n    const saved = await getState();\n    if (saved) {\n        root.getElementById('text-input').value = saved;\n        updateStats();\n    }\n}\n\ninit();",
  "tags": [
    "tools",
    "text",
    "development"
  ],
  "lastModifiedDate": 1769807039187,
  "createdDate": 1769807039187
};
