export default {
  "id": "countdown-timer",
  "name": "Countdown Timer",
  "description": "Set a countdown timer for your tasks or events.",
  "author": "Infinition",
  "authorUrl": "https://github.com/infinition",
  "html": "<div class=\"widget-card\">\n  <div class=\"widget-header\">\n    <h4 class=\"widget-title\" id=\"event-title\">⏳ Event Countdown</h4>\n  </div>\n  \n  <div class=\"countdown-grid\">\n    <div class=\"time-box\">\n      <span id=\"days\">00</span>\n      <label>Days</label>\n    </div>\n    <div class=\"time-box\">\n      <span id=\"hours\">00</span>\n      <label>Hours</label>\n    </div>\n    <div class=\"time-box\">\n      <span id=\"mins\">00</span>\n      <label>Mins</label>\n    </div>\n    <div class=\"time-box\">\n      <span id=\"secs\">00</span>\n      <label>Secs</label>\n    </div>\n  </div>\n\n  <div class=\"settings-panel\">\n    <div class=\"input-group\">\n      <input type=\"text\" id=\"event-name\" placeholder=\"Event Name...\">\n      <input type=\"date\" id=\"event-date\">\n    </div>\n    <div class=\"btn-row\">\n      <button id=\"btn-set\" class=\"btn-primary\">Set Event</button>\n      <button id=\"btn-clear\" class=\"btn-secondary\">Clear</button>\n    </div>\n  </div>\n</div>",
  "css": ":host { display: flex; flex-direction: column; width: 100%; height: 100%; min-width: 0; min-height: 0; overflow: hidden; box-sizing: border-box; font-family: var(--font-interface); } * { box-sizing: border-box; } .widget-card { background: var(--background-secondary); border: 1px solid var(--background-modifier-border); border-radius: 16px; padding: 1.5rem; box-shadow: var(--shadow-s); text-align: center; width: 100%; height: 100%; min-width: 0; min-height: 0; overflow: hidden; display: flex; flex-direction: column; } .widget-header { margin-bottom: 1.5rem; } .widget-title { margin: 0; font-size: 0.9rem; font-weight: 800; color: var(--text-accent); text-transform: uppercase; letter-spacing: 1px; } .countdown-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 1.5rem; } .time-box { background: var(--background-primary); padding: 12px 4px; border-radius: 12px; border: 1px solid var(--background-modifier-border); transition: transform 0.2s ease; } .time-box:hover { transform: translateY(-2px); border-color: var(--interactive-accent); } .time-box span { display: block; font-size: 1.5rem; font-weight: 900; font-family: var(--font-monospace); color: var(--interactive-accent); } .time-box label { font-size: 0.6rem; font-weight: 700; text-transform: uppercase; color: var(--text-muted); } .settings-panel { background: var(--background-primary-alt); padding: 12px; border-radius: 12px; border: 1px solid var(--background-modifier-border); } .input-group { display: flex; flex-direction: column; gap: 8px; margin-bottom: 12px; } .input-group input { background: var(--background-primary); border: 1px solid var(--background-modifier-border); color: var(--text-normal); padding: 8px 12px; border-radius: 6px; font-size: 0.85rem; outline: none; width: 100%; } .input-group input:focus { border-color: var(--interactive-accent); } .btn-row { display: flex; gap: 8px; } button { flex: 1; padding: 10px; border-radius: 6px; font-weight: 700; font-size: 0.85rem; cursor: pointer; border: none; transition: opacity 0.2s; } button:hover { opacity: 0.9; } .btn-primary { background: var(--interactive-accent); color: var(--text-on-accent); } .btn-secondary { background: var(--background-modifier-border); color: var(--text-normal); }",
  "js": "var state = {\n    title: 'Next Vacation',\n    targetDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30).toISOString().split('T')[0]\n};\nvar timerId = null;\n\nfunction startCountdown() {\n    if (timerId) clearInterval(timerId);\n    \n    var titleEl = api.root.getElementById('event-title');\n    if (titleEl) titleEl.innerText = '⏳ ' + state.title;\n    \n    timerId = setInterval(function() {\n        var now = new Date().getTime();\n        var target = new Date(state.targetDate).getTime();\n        var diff = target - now;\n        \n        if (diff <= 0) {\n            clearInterval(timerId);\n            updateDisplay(0, 0, 0, 0);\n            return;\n        }\n        \n        var days = Math.floor(diff / (1000 * 60 * 60 * 24));\n        var hours = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));\n        var mins = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));\n        var secs = Math.floor((diff % (1000 * 60)) / 1000);\n        \n        updateDisplay(days, hours, mins, secs);\n    }, 1000);\n}\n\nfunction updateDisplay(d, h, m, s) {\n    var dEl = api.root.getElementById('days');\n    var hEl = api.root.getElementById('hours');\n    var mEl = api.root.getElementById('mins');\n    var sEl = api.root.getElementById('secs');\n    \n    if (dEl) dEl.innerText = d.toString().padStart(2, '0');\n    if (hEl) hEl.innerText = h.toString().padStart(2, '0');\n    if (mEl) mEl.innerText = m.toString().padStart(2, '0');\n    if (sEl) sEl.innerText = s.toString().padStart(2, '0');\n}\n\nfunction updateEvent() {\n    var nameInput = api.root.getElementById('event-name');\n    var dateInput = api.root.getElementById('event-date');\n    \n    state.title = nameInput.value.trim() || 'Event';\n    state.targetDate = dateInput.value;\n    \n    if (state.targetDate) {\n        startCountdown();\n        api.saveState(state);\n    }\n}\n\nfunction clearEvent() {\n    state = {\n        title: 'Event',\n        targetDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString().split('T')[0]\n    };\n    var nameInput = api.root.getElementById('event-name');\n    var dateInput = api.root.getElementById('event-date');\n    \n    if (nameInput) nameInput.value = '';\n    if (dateInput) dateInput.value = state.targetDate;\n    \n    startCountdown();\n    api.saveState(state);\n}\n\nasync function init() {\n    var saved = await api.getState();\n    if (saved) state = saved;\n    \n    var nameInput = api.root.getElementById('event-name');\n    var dateInput = api.root.getElementById('event-date');\n    var btnSet = api.root.getElementById('btn-set');\n    var btnClear = api.root.getElementById('btn-clear');\n    \n    if (nameInput) nameInput.value = state.title;\n    if (dateInput) dateInput.value = state.targetDate;\n    \n    if (btnSet) btnSet.onclick = updateEvent;\n    if (btnClear) btnClear.onclick = clearEvent;\n    \n    startCountdown();\n}\n\ninit();",
  "tags": [
    "time",
    "productivity",
    "events"
  ],
  "lastModifiedDate": 1769807039537,
  "createdDate": 1769807039537
};
