export default {
  "id": "daily-affirmations",
  "name": "Daily Quotes",
  "description": "Get a daily dose of positive affirmations.",
  "author": "Infinition",
  "authorUrl": "https://github.com/infinition",
  "html": "<div class=\"widget-card\">\n  <div class=\"quote-icon\">\"</div>\n  <div class=\"quote-container\">\n    <div class=\"affirmation\" id=\"affirmation-text\">Loading quotes...</div>\n    <div class=\"author\" id=\"quote-author\"></div>\n  </div>\n  <button class=\"btn-next\" id=\"btn-next\">New Quote</button>\n  <div class=\"footer\" id=\"last-updated\">Last updated: Just now</div>\n</div>",
  "css": ":host { display: block; margin: 1.5rem 0; font-family: var(--font-interface); }\n.widget-card {\n    background: var(--background-secondary);\n    color: var(--text-normal);\n    border-radius: 16px;\n    padding: 2rem;\n    box-shadow: var(--shadow-s);\n    border: 1px solid var(--background-modifier-border);\n    text-align: center;\n    position: relative;\n    overflow: hidden;\n}\n\n.quote-icon {\n    position: absolute;\n    top: -10px;\n    left: 20px;\n    font-size: 6rem;\n    opacity: 0.05;\n    font-family: serif;\n    color: var(--interactive-accent);\n    flex-shrink: 0;\n}\n\n.quote-container {\n    flex: 1;\n    min-height: 80px;\n    display: flex;\n    flex-direction: column;\n    align-items: center;\n    justify-content: center;\n    margin-bottom: 1.5rem;\n    overflow: auto;\n}\n\n.affirmation {\n    font-size: 1.2rem;\n    font-weight: 600;\n    line-height: 1.5;\n    margin-bottom: 0.5rem;\n    color: var(--text-normal);\n}\n\n.author {\n    font-size: 0.9rem;\n    font-style: italic;\n    color: var(--text-muted);\n    font-weight: 500;\n}\n\n.btn-next { flex-shrink: 0; background: var(--interactive-accent); color: var(--text-on-accent); border: none; padding: 10px 20px; border-radius: 8px; font-weight: 600; font-size: 0.8rem; cursor: pointer; transition: opacity 0.2s; }\n.btn-next:hover { opacity: 0.8; }\n\n.footer { flex-shrink: 0; margin-top: 1.5rem; font-size: 0.65rem; color: var(--text-faint); font-weight: 500; }",
  "js": "const { root, saveState, getState } = api;\nconst QUOTES_URL = 'https://raw.githubusercontent.com/dwyl/quotes/main/quotes.json';\nlet quotes = [];\nlet updateInterval;\n\nasync function fetchQuotes() {\n    try {\n        const response = await fetch(QUOTES_URL);\n        quotes = await response.json();\n        return true;\n    } catch (e) {\n        console.error('Failed to fetch quotes', e);\n        root.getElementById('affirmation-text').innerText = 'Failed to load quotes.';\n        return false;\n    }\n}\n\nfunction displayRandomQuote() {\n    if (quotes.length === 0) return;\n    \n    const quote = quotes[Math.floor(Math.random() * quotes.length)];\n    const time = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });\n    \n    root.getElementById('affirmation-text').innerText = quote.text;\n    root.getElementById('quote-author').innerText = quote.author ? '- ' + quote.author : '';\n    root.getElementById('last-updated').innerText = 'Last updated: ' + time;\n    \n    saveState({ quote, time });\n}\n\nasync function init() {\n    const saved = await getState();\n    if (saved && saved.quote) {\n        root.getElementById('affirmation-text').innerText = saved.quote.text;\n        root.getElementById('quote-author').innerText = saved.quote.author ? '- ' + saved.quote.author : '';\n        root.getElementById('last-updated').innerText = 'Last updated: ' + saved.time;\n    }\n\n    const success = await fetchQuotes();\n    if (success) {\n        if (!saved) displayRandomQuote();\n        \n        // Update every 10 minutes\n        clearInterval(updateInterval);\n        updateInterval = setInterval(displayRandomQuote, 10 * 60 * 1000);\n    }\n    \n    root.getElementById('btn-next').onclick = displayRandomQuote;\n}\n\ninit();",
  "tags": [
    "quotes",
    "motivation",
    "development"
  ],
  "lastModifiedDate": 1769807040590,
  "createdDate": 1769807040590
};
