export default {
  "id": "data-explorer",
  "name": "Data Explorer Pro",
  "description": "Explore and edit any text-based file in your vault (JSON, CSV, LOG, XML, etc.).",
  "author": "Infinition",
  "authorUrl": "https://github.com/infinition",
  "html": "<div class=\"data-container\">\n  <h4>📊 Data Explorer Pro</h4>\n  \n  <div class=\"row\">\n    <label>1. Search & Select File:</label>\n    <div class=\"search-wrapper\">\n      <input type=\"text\" id=\"file-search\" list=\"data-file-list\" placeholder=\"Search files (json, csv, log, xml...)\" onchange=\"handleFileChange()\">\n      <datalist id=\"data-file-list\"></datalist>\n      <button onclick=\"refreshFileList()\" class=\"mini-btn\">🔄</button>\n    </div>\n  </div>\n\n  <div class=\"row\">\n    <div class=\"header-row\">\n      <label>2. Editor:</label>\n      <button onclick=\"saveData()\" class=\"save-btn\">💾 Save Changes</button>\n    </div>\n    <textarea id=\"data-editor\" placeholder=\"Select a file to edit...\"></textarea>\n  </div>\n\n  <div id=\"csv-stats\" class=\"stats-box\" style=\"display:none\">\n    <div id=\"row-count\">Rows: 0</div>\n    <div id=\"col-count\">Columns: 0</div>\n  </div>\n\n  <div id=\"status-bar\" class=\"status\">Ready</div>\n</div>",
  "css": ".data-container {\n    background: var(--background-secondary);\n    border: 1px solid var(--background-modifier-border);\n    border-radius: 12px;\n    padding: 15px;\n    color: var(--text-normal);\n    box-sizing: border-box;\n    overflow: hidden;\n    min-width: 0;\n    max-width: 100%;\n}\n.row {\n    margin-bottom: 12px;\n    display: flex;\n    flex-direction: column;\n    gap: 6px;\n    min-width: 0;\n}\n.header-row {\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n}\n.row label {\n    font-size: 0.7rem;\n    font-weight: 700;\n    text-transform: uppercase;\n    color: var(--text-muted);\n}\n.search-wrapper {\n    display: flex;\n    gap: 8px;\n    min-width: 0;\n}\n#file-search, #data-editor {\n    width: 100%;\n    min-width: 0;\n    max-width: 100%;\n    box-sizing: border-box;\n    background: var(--background-primary);\n    color: var(--text-normal);\n    border: 1px solid var(--background-modifier-border);\n    border-radius: 6px;\n    padding: 8px;\n    font-size: 0.85rem;\n    outline: none;\n}\n#file-search:focus, #data-editor:focus {\n    border-color: var(--interactive-accent);\n}\n#data-editor {\n    flex: 1;\n    min-height: 80px;\n    font-family: var(--font-monospace);\n    resize: none;\n    color: var(--text-accent);\n    box-sizing: border-box;\n}\n#csv-stats, .status { flex-shrink: 0; }\n.stats-box {\n    display: flex;\n    gap: 15px;\n    font-size: 0.7rem;\n    color: var(--text-muted);\n    margin-top: 5px;\n    padding: 5px 10px;\n    background: var(--background-modifier-border);\n    border-radius: 4px;\n}\n.mini-btn {\n    padding: 8px;\n    background: var(--background-primary);\n    border: 1px solid var(--background-modifier-border);\n    border-radius: 6px;\n    cursor: pointer;\n}\n.save-btn {\n    background: var(--background-modifier-success);\n    color: white;\n    border: none;\n    padding: 4px 10px;\n    border-radius: 4px;\n    font-size: 0.75rem;\n    cursor: pointer;\n    font-weight: 600;\n}\n.status {\n    font-size: 0.65rem;\n    color: var(--text-muted);\n    margin-top: 10px;\n    font-style: italic;\n    border-top: 1px solid var(--background-modifier-border);\n    padding-top: 8px;\n}",
  "js": "const TEXT_EXTENSIONS = ['json', 'csv', 'log', 'xml', 'txt', 'md', 'yaml', 'yml', 'css', 'js', 'ts'];\n\nasync function refreshFileList() {\n    const datalist = root.getElementById('data-file-list');\n    const allFiles = await api.getFiles();\n    \n    const files = allFiles.filter(f => {\n        const ext = f.split('.').pop().toLowerCase();\n        return TEXT_EXTENSIONS.includes(ext);\n    });\n    \n    datalist.innerHTML = '';\n    files.forEach(file => {\n        const option = document.createElement('option');\n        option.value = file;\n        datalist.appendChild(option);\n    });\n    setStatus(\"File list updated (\" + files.length + \" files)\");\n    await loadFileContent();\n}\n\nasync function handleFileChange() {\n    const path = root.getElementById('file-search').value;\n    if (!path || !path.includes('.')) return;\n    \n    await api.saveState({ lastPath: path });\n    await loadFileContent();\n}\n\nasync function loadFileContent() {\n    const path = root.getElementById('file-search').value;\n    const editor = root.getElementById('data-editor');\n    const stats = root.getElementById('csv-stats');\n\n    if (!path || !path.includes('.')) {\n        editor.value = \"\";\n        stats.style.display = 'none';\n        return;\n    }\n\n    setStatus(\"Loading \" + path + \"...\");\n    const content = await api.readFile(path);\n\n    if (content === null) {\n        setStatus(\"File not found\");\n        editor.value = \"\";\n        return;\n    }\n\n    editor.value = content;\n    \n    if (path.endsWith('.csv')) {\n        const data = api.parseCSV(content);\n        if (data.length > 0) {\n            stats.style.display = 'flex';\n            root.getElementById('row-count').innerText = `Rows: ${data.length}`;\n            root.getElementById('col-count').innerText = `Columns: ${Object.keys(data[0]).length}`;\n        }\n    } else {\n        stats.style.display = 'none';\n    }\n    setStatus(\"Loaded: \" + path);\n}\n\nasync function saveData() {\n    const path = root.getElementById('file-search').value;\n    const content = root.getElementById('data-editor').value;\n    \n    if (!path) {\n        new Notice(\"Please select a file first\");\n        return;\n    }\n\n    setStatus(\"Saving...\");\n    await api.writeFile(path, content);\n    new Notice(\"Saved successfully!\");\n    setStatus(\"Saved: \" + path);\n    \n    if (path.endsWith('.csv')) loadFileContent();\n}\n\nfunction setStatus(msg) {\n    root.getElementById('status-bar').innerText = msg;\n}\n\nasync function init() {\n    refreshFileList();\n    const saved = await api.getState();\n    if (saved && saved.lastPath) {\n        root.getElementById('file-search').value = saved.lastPath;\n        loadFileContent();\n    }\n}\n\ninit();",
  "tags": [
    "data",
    "test",
    "explorer",
    "editor",
    "persistence",
    "all-files"
  ],
  "lastModifiedDate": 1769807041112,
  "createdDate": 1769807041112
};
