export default {
    "id": "flash-capture",
    "name": "Flash Capture",
    "description": "Capturez vos idées instantanément vers une 'Inbox' sans changer de contexte. Zéro friction.",
    "author": "Infinition",
    "defaultSizePx": { "width": 300, "height": 200 },
    "html": "<div class=\"flash-wrapper\" id=\"flash-root\">\n  <div class=\"status-pill\" id=\"status-pill\">Ready</div>\n  <div class=\"input-container\">\n    <textarea id=\"flash-input\" placeholder=\"Une idée ? Tapez et faites Ctrl+Enter...\" spellcheck=\"false\"></textarea>\n    <button id=\"btn-send\" class=\"send-btn\">\n      <svg viewBox=\"0 0 24 24\" width=\"20\" height=\"20\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><line x1=\"22\" y1=\"2\" x2=\"11\" y2=\"13\"></line><polygon points=\"22 2 15 22 11 13 2 9 22 2\"></polygon></svg>\n    </button>\n  </div>\n  <div class=\"success-overlay\" id=\"success-overlay\">\n    <svg class=\"check-icon\" viewBox=\"0 0 24 24\" width=\"48\" height=\"48\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"><polyline points=\"20 6 9 17 4 12\"></polyline></svg>\n    <span>Capturé !</span>\n  </div>\n</div>",
    "css": ":host { --fl-bg: var(--background-primary); --fl-input: var(--background-secondary); --fl-accent: var(--interactive-accent); --fl-text: var(--text-normal); display: flex; flex-direction: column; width: 100%; height: 100%; overflow: hidden; font-family: var(--font-interface); }\n\n.flash-wrapper { flex: 1; display: flex; flex-direction: column; padding: 12px; background: var(--fl-bg); position: relative; }\n\n.status-pill { align-self: flex-end; font-size: 0.65rem; color: var(--text-muted); text-transform: uppercase; font-weight: 700; margin-bottom: 8px; opacity: 0.5; transition: opacity 0.3s; }\n\n.input-container { flex: 1; display: flex; flex-direction: column; gap: 8px; position: relative; }\n\ntextarea { flex: 1; resize: none; border: 1px solid var(--background-modifier-border); background: var(--fl-input); color: var(--fl-text); border-radius: 8px; padding: 12px; font-family: var(--font-text); font-size: 0.9rem; line-height: 1.4; outline: none; transition: border 0.2s, box-shadow 0.2s; }\ntextarea:focus { border-color: var(--fl-accent); box-shadow: 0 0 0 2px rgba(var(--interactive-accent-rgb), 0.2); }\ntextarea::placeholder { color: var(--text-muted); font-style: italic; }\n\n.send-btn { position: absolute; bottom: 8px; right: 8px; width: 32px; height: 32px; background: var(--fl-accent); color: var(--text-on-accent); border: none; border-radius: 6px; cursor: pointer; display: flex; align-items: center; justify-content: center; transition: transform 0.1s, opacity 0.2s; opacity: 0; pointer-events: none; }\ntextarea:not(:placeholder-shown) + .send-btn { opacity: 1; pointer-events: auto; }\n.send-btn:hover { transform: scale(1.05); }\n.send-btn:active { transform: scale(0.95); }\n\n/* Success Animation */\n.success-overlay { position: absolute; inset: 0; background: rgba(var(--background-primary-rgb), 0.9); display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 10px; color: var(--fl-accent); opacity: 0; pointer-events: none; transition: opacity 0.3s; z-index: 10; }\n.success-overlay.active { opacity: 1; }\n.check-icon { stroke-dasharray: 50; stroke-dashoffset: 50; transition: stroke-dashoffset 0.5s ease-in-out; }\n.success-overlay.active .check-icon { stroke-dashoffset: 0; }\n.success-overlay span { font-weight: 800; font-size: 1.2rem; transform: translateY(10px); opacity: 0; transition: all 0.3s 0.2s; }\n.success-overlay.active span { transform: translateY(0); opacity: 1; }",
    "js": "var root = api.root;\nvar app = window.app || api.app;\n\n// --- Config ---\nconst INBOX_FILE = \"INBOX.md\";\nconst TIMESTAMP_FORMAT = true;\n\nfunction qs(sel) { return root.querySelector(sel); }\n\nasync function appendToInbox(text) {\n  if (!text.trim()) return;\n  \n  var now = new Date();\n  var time = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });\n  var line = TIMESTAMP_FORMAT ? `- [ ] ${time} ${text}` : `- [ ] ${text}`;\n  \n  try {\n    var file = app.vault.getAbstractFileByPath(INBOX_FILE);\n    if (!file) {\n      // Create if not exists\n      await app.vault.create(INBOX_FILE, \"# Inbox\\n\\n\" + line);\n    } else {\n      // Append\n      var content = await app.vault.read(file);\n      // Ensure newline\n      if(content && !content.endsWith('\\n')) content += '\\n';\n      await app.vault.modify(file, content + line + '\\n');\n    }\n    showSuccess();\n  } catch (e) {\n    console.error(e);\n    qs('#status-pill').textContent = \"Error!\";\n    qs('#status-pill').style.color = \"red\";\n  }\n}\n\nfunction showSuccess() {\n  var overlay = qs('#success-overlay');\n  var ta = qs('#flash-input');\n  \n  ta.blur();\n  overlay.classList.add('active');\n  \n  setTimeout(() => {\n    ta.value = '';\n    overlay.classList.remove('active');\n    setTimeout(() => ta.focus(), 100);\n  }, 1200);\n}\n\nfunction init() {\n  var ta = qs('#flash-input');\n  var btn = qs('#btn-send');\n  \n  // Handle Enter (Ctrl+Enter or just Enter if preferred)\n  ta.onkeydown = function(e) {\n    if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {\n      appendToInbox(ta.value);\n    }\n  };\n  \n  btn.onclick = () => appendToInbox(ta.value);\n  \n  // Auto focus if needed\n  // ta.focus(); \n}\n\ninit();",
    "tags": ["productivity", "capture", "gtd", "fast", "inbox"]
  };