export default {
  "id": "habit-tracker",
  "name": "Habit Tracker",
  "description": "Track your daily habits and build long-term streaks.",
  "author": "Infinition",
  "authorUrl": "https://github.com/infinition",
  "html": "<div class=\"widget-card\">\n  <div class=\"widget-header\">\n    <h4 class=\"widget-title\">✅ Habit Tracker</h4>\n    <button class=\"btn-icon\" id=\"btn-add-habit\">+</button>\n  </div>\n  \n  <div class=\"habit-grid-header\">\n    <span class=\"label-habit\">Habit</span>\n    <div class=\"days-labels\">\n      <span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span>\n    </div>\n  </div>\n\n  <div id=\"habit-list\"></div>\n</div>",
  "css": ":host { display: flex; flex-direction: column; width: 100%; height: 100%; min-width: 0; min-height: 0; overflow: hidden; box-sizing: border-box; font-family: var(--font-interface); }\n.widget-card {\n    background: var(--background-secondary);\n    border: 1px solid var(--divider-color);\n    border-radius: 12px;\n    padding: 1.25rem;\n    box-shadow: 0 4px 12px rgba(0,0,0,0.08);\n    width: 100%;\n    height: 100%;\n    min-width: 0;\n    min-height: 0;\n    overflow: hidden;\n    display: flex;\n    flex-direction: column;\n}\n.widget-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem; flex-shrink: 0; }\n.widget-title { margin: 0; font-size: 0.9rem; font-weight: 600; color: var(--text-accent); text-transform: uppercase; letter-spacing: 0.05em; }\n\n.btn-icon {\n    background: var(--interactive-accent);\n    color: white;\n    border: none;\n    width: 28px;\n    height: 28px;\n    border-radius: 50%;\n    cursor: pointer;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    font-weight: bold;\n    transition: filter 0.2s;\n}\n.btn-icon:hover { filter: brightness(1.1); }\n\n.btn-delete {\n    background: transparent;\n    color: var(--text-muted);\n    border: none;\n    cursor: pointer;\n    font-size: 1.2rem;\n    padding: 0 8px;\n    opacity: 0;\n    transition: opacity 0.2s, color 0.2s;\n}\n.habit-row:hover .btn-delete { opacity: 1; }\n.btn-delete:hover { color: var(--text-danger); }\n\n.habit-grid-header {\n    display: grid;\n    grid-template-columns: 1fr auto;\n    font-size: 0.7rem;\n    font-weight: 700;\n    color: var(--text-muted);\n    margin-bottom: 0.75rem;\n    padding-right: 32px;\n    text-transform: uppercase;\n}\n\n.days-labels {\n    display: grid;\n    grid-template-columns: repeat(7, 28px);\n    text-align: center;\n}\n\n.habit-row {\n    display: grid;\n    grid-template-columns: 1fr auto auto;\n    align-items: center;\n    margin-bottom: 0.5rem;\n    gap: 8px;\n    padding: 4px;\n    border-radius: 8px;\n    transition: background 0.2s;\n}\n.habit-row:hover { background: var(--background-primary-alt); }\n\n.habit-name {\n    border: none;\n    background: transparent;\n    color: var(--text-normal);\n    font-size: 0.85rem;\n    outline: none;\n    padding: 4px;\n    border-radius: 4px;\n    width: 100%;\n}\n.habit-name:focus { background: var(--background-primary); box-shadow: 0 0 0 1px var(--divider-color); }\n\n.dots-container {\n    display: grid;\n    grid-template-columns: repeat(7, 28px);\n}\n\n.dot {\n    width: 18px;\n    height: 18px;\n    border-radius: 5px;\n    border: 2px solid var(--divider-color);\n    margin: auto;\n    cursor: pointer;\n    transition: all 0.2s cubic-bezier(0.175, 0.885, 0.32, 1.275);\n}\n\n.dot.active {\n    background: var(--interactive-accent);\n    border-color: var(--interactive-accent);\n    transform: scale(1.1);\n}",
  "js": "var habits = [{ name: 'Reading', done: [false, false, false, false, false, false, false] }, { name: 'Meditation', done: [false, false, false, false, false, false, false] }];\n\nfunction render() {\n    var container = api.root.getElementById('habit-list');\n    container.innerHTML = '';\n    habits.forEach(function(habit, hIdx) {\n        var row = document.createElement('div');\n        row.className = 'habit-row';\n        var input = document.createElement('input');\n        input.className = 'habit-name';\n        input.value = habit.name;\n        input.onchange = function(e) {\n            habits[hIdx].name = e.target.value;\n            api.saveState(habits);\n        };\n        var dots = document.createElement('div');\n        dots.className = 'dots-container';\n        habit.done.forEach(function(status, dIdx) {\n            var dot = document.createElement('div');\n            dot.className = 'dot' + (status ? ' active' : '');\n            dot.onclick = function() {\n                habits[hIdx].done[dIdx] = !habits[hIdx].done[dIdx];\n                api.saveState(habits);\n                render();\n            };\n            dots.appendChild(dot);\n        });\n        var btnDel = document.createElement('button');\n        btnDel.className = 'btn-delete';\n        btnDel.innerHTML = '×';\n        btnDel.onclick = function() {\n            habits.splice(hIdx, 1);\n            api.saveState(habits);\n            render();\n        };\n        row.appendChild(input);\n        row.appendChild(dots);\n        row.appendChild(btnDel);\n        container.appendChild(row);\n    });\n}\n\nfunction addHabit() {\n    habits.push({ name: 'New Habit', done: [false, false, false, false, false, false, false] });\n    render();\n    api.saveState(habits);\n}\n\nasync function init() {\n    var saved = await api.getState();\n    if (Array.isArray(saved)) {\n        habits = saved;\n    }\n    \n    api.root.getElementById('btn-add-habit').onclick = addHabit;\n    \n    render();\n}\n\ninit();",
  "tags": [
    "productivity",
    "habits",
    "tracker"
  ],
  "lastModifiedDate": 1769807044330,
  "createdDate": 1769807044330
};
