export default {
  "id": "scratchpad",
  "name": "Scratchpad",
  "description": "A simple and quick scratchpad for your notes and ideas.",
  "author": "Infinition",
  "authorUrl": "https://github.com/infinition",
  "html": "<div class=\"widget-card\"><div class=\"widget-header\"><span class=\"widget-icon\">📝</span><h4 class=\"widget-title\">Scratchpad</h4><button class=\"btn-icon\" id=\"btn-copy\">📋</button><button class=\"btn-icon\" id=\"btn-clear\">🗑️</button></div><div class=\"editor-container\"><textarea id=\"note-area\" placeholder=\"Start typing...\"></textarea></div><div class=\"widget-footer\"><span id=\"word-count\">0</span> words · <span id=\"char-count\">0</span> chars</div></div>",
  "css": ":host { display: flex; flex-direction: column; width: 100%; height: 100%; min-width: 0; min-height: 0; overflow: hidden; box-sizing: border-box; font-family: var(--font-interface); }\n* { box-sizing: border-box; }\n.widget-card { flex: 1; display: flex; flex-direction: column; min-width: 0; min-height: 0; background: var(--background-secondary); border: 1px solid var(--background-modifier-border); border-radius: 12px; padding: 1rem; overflow: hidden; }\n.widget-header { flex-shrink: 0; display: flex; align-items: center; gap: 8px; margin-bottom: 0.75rem; min-width: 0; }\n.widget-icon { font-size: 1.2rem; }\n.widget-title { margin: 0; font-size: 0.95rem; font-weight: 700; flex: 1; min-width: 0; }\n.btn-icon { background: var(--background-primary); border: 1px solid var(--background-modifier-border); padding: 6px 10px; border-radius: 8px; cursor: pointer; }\n.btn-icon:hover { background: var(--background-modifier-hover); }\n.editor-container { flex: 1; min-height: 0; min-width: 0; display: flex; flex-direction: column; }\n#note-area { flex: 1; min-height: 80px; width: 100%; min-width: 0; max-width: 100%; padding: 10px; border-radius: 8px; border: 1px solid var(--background-modifier-border); font-family: var(--font-monospace); font-size: 0.9rem; resize: vertical; box-sizing: border-box; }\n.widget-footer { margin-top: 0.5rem; font-size: 0.75rem; color: var(--text-muted); }",
  "js": "const { root, saveState, getState } = api;\nlet state = { text: '' };\nlet saveTimeout;\nfunction updateStats() {\n  const area = root.getElementById('note-area');\n  if (!area) return;\n  const t = area.value;\n  root.getElementById('char-count').innerText = t.length;\n  root.getElementById('word-count').innerText = t.trim() ? t.trim().split(/\\s+/).length : 0;\n}\nfunction save() {\n  const area = root.getElementById('note-area');\n  if (!area) return;\n  state.text = area.value;\n  saveState(state);\n}\nroot.getElementById('btn-clear').onclick = () => { if (confirm('Clear?')) { root.getElementById('note-area').value = ''; state.text = ''; saveState(state); updateStats(); } };\nroot.getElementById('btn-copy').onclick = () => { navigator.clipboard.writeText(root.getElementById('note-area').value); };\nasync function init() {\n  const saved = await getState();\n  if (saved && saved.text) state = saved;\n  const area = root.getElementById('note-area');\n  area.value = state.text || '';\n  area.oninput = () => { updateStats(); clearTimeout(saveTimeout); saveTimeout = setTimeout(save, 800); };\n  updateStats();\n}\ninit();",
  "tags": ["notes", "productivity", "text", "editor"]
};
