export default {
    "id": "vault-time-machine",
    "name": "Time Machine",
    "description": "On this day... Redécouvrez vos notes créées à cette date précise les années précédentes.",
    "author": "Infinition",
    "defaultSizePx": { "width": 300, "height": 500 },
    "html": "<div class=\"tm-wrapper\" id=\"tm-root\">\n  <div class=\"tm-header\">\n    <div class=\"date-display\">\n      <span id=\"disp-day\">31</span>\n      <span id=\"disp-month\">JAN</span>\n    </div>\n    <div class=\"header-label\">TIME MACHINE</div>\n  </div>\n\n  <div class=\"timeline-container\" id=\"timeline-list\">\n    \n    <div class=\"loading\">Scan du continuum...</div>\n  </div>\n</div>",
    "css": ":host { --tm-bg: var(--background-primary); --tm-line: var(--background-modifier-border); --tm-accent: var(--interactive-accent); display: flex; flex-direction: column; width: 100%; height: 100%; overflow: hidden; font-family: var(--font-interface); }\n\n.tm-wrapper { flex: 1; display: flex; flex-direction: column; background: var(--tm-bg); }\n\n.tm-header { flex-shrink: 0; padding: 20px; background: var(--background-secondary); border-bottom: 1px solid var(--tm-line); display: flex; align-items: center; justify-content: space-between; }\n.date-display { display: flex; flex-direction: column; align-items: center; background: var(--tm-bg); padding: 8px 12px; border-radius: 8px; border: 1px solid var(--tm-line); box-shadow: var(--shadow-s); }\n#disp-day { font-size: 1.2rem; font-weight: 800; color: var(--text-normal); line-height: 1; }\n#disp-month { font-size: 0.7rem; font-weight: 700; color: var(--tm-accent); text-transform: uppercase; letter-spacing: 1px; }\n.header-label { font-family: 'Courier New', monospace; font-weight: 700; letter-spacing: 2px; color: var(--text-muted); opacity: 0.5; }\n\n.timeline-container { flex: 1; overflow-y: auto; padding: 20px; position: relative; }\n.timeline-container::before { content: ''; position: absolute; top: 0; bottom: 0; left: 30px; width: 2px; background: var(--tm-line); z-index: 0; }\n\n.year-marker { margin-bottom: 20px; position: relative; z-index: 1; }\n.year-label { display: inline-block; background: var(--tm-accent); color: white; font-size: 0.75rem; font-weight: 700; padding: 2px 8px; border-radius: 12px; margin-left: 6px; margin-bottom: 8px; }\n\n.note-entry { position: relative; margin-left: 24px; background: var(--background-secondary); border: 1px solid var(--tm-line); border-radius: 8px; padding: 12px; margin-bottom: 12px; cursor: pointer; transition: transform 0.2s; box-shadow: var(--shadow-s); }\n.note-entry:hover { transform: translateX(4px); border-color: var(--tm-accent); }\n.note-entry::after { content: ''; position: absolute; top: 15px; left: -29px; width: 10px; height: 10px; background: var(--background-primary); border: 2px solid var(--tm-accent); border-radius: 50%; z-index: 2; }\n\n.entry-title { font-weight: 700; font-size: 0.9rem; color: var(--text-normal); margin-bottom: 4px; }\n.entry-meta { font-size: 0.7rem; color: var(--text-muted); display: flex; justify-content: space-between; }\n\n.loading { text-align: center; color: var(--text-muted); margin-top: 40px; font-style: italic; }",
    "js": "var root = api.root;\nvar app = window.app || api.app;\n\nconst MONTHS = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];\n\nfunction qs(sel) { return root.querySelector(sel); }\n\nfunction getHistory() {\n  var today = new Date();\n  var tMonth = today.getMonth();\n  var tDate = today.getDate();\n  \n  qs('#disp-day').textContent = tDate;\n  qs('#disp-month').textContent = MONTHS[tMonth];\n\n  var files = app.vault.getFiles();\n  var matches = [];\n\n  files.forEach(f => {\n    var ctime = new Date(f.stat.ctime);\n    // Check if same month and date, but NOT same year (optional, can include today)\n    if (ctime.getMonth() === tMonth && ctime.getDate() === tDate && ctime.getFullYear() !== today.getFullYear()) {\n      matches.push({ file: f, year: ctime.getFullYear(), time: ctime });\n    }\n  });\n\n  // Sort by year descending (newest first)\n  matches.sort((a, b) => b.year - a.year);\n  renderTimeline(matches);\n}\n\nfunction renderTimeline(matches) {\n  var container = qs('#timeline-list');\n  container.innerHTML = '';\n\n  if (matches.length === 0) {\n    container.innerHTML = '<div style=\"text-align:center; color:var(--text-muted); padding:20px;\">Aucun souvenir trouvé pour ce jour.</div>';\n    return;\n  }\n\n  var currentYear = null;\n\n  matches.forEach(m => {\n    // Year Header if changed\n    if (m.year !== currentYear) {\n      currentYear = m.year;\n      var yh = document.createElement('div');\n      yh.className = 'year-marker';\n      yh.innerHTML = `<span class=\"year-label\">${currentYear}</span>`;\n      container.appendChild(yh);\n    }\n\n    // Note Card\n    var card = document.createElement('div');\n    card.className = 'note-entry';\n    card.innerHTML = `\n      <div class=\"entry-title\">${m.file.basename}</div>\n      <div class=\"entry-meta\">\n        <span>${m.time.toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}</span>\n        <span>${(m.file.stat.size / 1024).toFixed(1)} KB</span>\n      </div>\n    `;\n    card.onclick = () => app.workspace.openLinkText(m.file.path, '', false);\n    container.appendChild(card);\n  });\n}\n\nfunction init() {\n  setTimeout(getHistory, 100);\n}\n\ninit();",
    "tags": ["journaling", "history", "nostalgia", "review", "timeline"]
  };