export default {
    "id": "writing-heatmap",
    "name": "Writing Heatmap",
    "description": "Visualisez votre constance. Grille d'activité type GitHub basée sur vos modifications quotidiennes.",
    "author": "Infinition",
    "defaultSizePx": { "width": 300, "height": 220 },
    "html": "<div class=\"hm-wrapper\" id=\"hm-root\">\n  <div class=\"hm-header\">\n    <div class=\"hm-title\">ACTIVITY LOG</div>\n    <div class=\"hm-stats\">\n      <span id=\"streak-val\">0</span> day streak\n    </div>\n  </div>\n  \n  <div class=\"heatmap-grid\" id=\"grid\"></div>\n  \n  <div class=\"hm-legend\">\n    <span>Less</span>\n    <div class=\"legend-sq l0\"></div>\n    <div class=\"legend-sq l1\"></div>\n    <div class=\"legend-sq l2\"></div>\n    <div class=\"legend-sq l3\"></div>\n    <div class=\"legend-sq l4\"></div>\n    <span>More</span>\n  </div>\n\n  \n  <div id=\"tooltip\" class=\"tooltip\"></div>\n</div>",
    "css": ":host { --hm-bg: var(--background-primary); --hm-cell: var(--background-secondary-alt); --hm-gap: 3px; --hm-size: 10px; --c1: #0e4429; --c2: #006d32; --c3: #26a641; --c4: #39d353; font-family: var(--font-interface); display: flex; flex-direction: column; width: 100%; height: 100%; overflow: hidden; }\n/* Dark mode colors overlap adjustments */\n@media (prefers-color-scheme: dark) { :host { --c1: #0e4429; --c2: #006d32; --c3: #26a641; --c4: #39d353; } }\n/* Light mode colors */\n@media (prefers-color-scheme: light) { :host { --c1: #9be9a8; --c2: #40c463; --c3: #30a14e; --c4: #216e39; --hm-cell: #ebedf0; } }\n\n.hm-wrapper { flex: 1; background: var(--hm-bg); padding: 16px; display: flex; flex-direction: column; position: relative; }\n\n.hm-header { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 12px; }\n.hm-title { font-weight: 700; font-size: 0.75rem; color: var(--text-normal); }\n.hm-stats { font-size: 0.7rem; color: var(--text-muted); }\n#streak-val { color: var(--interactive-accent); font-weight: 800; }\n\n.heatmap-grid { display: flex; flex-wrap: wrap; gap: var(--hm-gap); align-content: flex-start; }\n\n.day-sq { width: var(--hm-size); height: var(--hm-size); background: var(--hm-cell); border-radius: 2px; cursor: pointer; transition: transform 0.1s; }\n.day-sq:hover { transform: scale(1.4); border: 1px solid var(--text-normal); z-index: 2; }\n\n.l0 { background: var(--hm-cell); }\n.l1 { background: var(--c1); }\n.l2 { background: var(--c2); }\n.l3 { background: var(--c3); }\n.l4 { background: var(--c4); }\n\n.hm-legend { display: flex; align-items: center; gap: 4px; font-size: 0.6rem; color: var(--text-muted); margin-top: auto; justify-content: flex-end; }\n.legend-sq { width: 8px; height: 8px; border-radius: 2px; }\n\n.tooltip { position: absolute; background: var(--background-modifier-message); color: var(--text-normal); padding: 4px 8px; border-radius: 4px; font-size: 0.7rem; pointer-events: none; opacity: 0; transition: opacity 0.2s; box-shadow: 0 4px 10px rgba(0,0,0,0.5); z-index: 100; font-weight: 600; white-space: nowrap; transform: translate(-50%, -120%); }",
    "js": "var root = api.root;\nvar app = window.app || api.app;\n\nfunction qs(sel) { return root.querySelector(sel); }\n\n// Generate last ~90 days data\nfunction generateData() {\n  var today = new Date();\n  var data = {};\n  \n  // Initialize last 112 days (16 weeks * 7 days)\n  for(var i=112; i>=0; i--) {\n    var d = new Date();\n    d.setDate(today.getDate() - i);\n    var key = d.toISOString().split('T')[0];\n    data[key] = { count: 0, date: d };\n  }\n\n  // Count file mtimes\n  var files = app.vault.getFiles();\n  files.forEach(f => {\n    var mtime = new Date(f.stat.mtime);\n    var key = mtime.toISOString().split('T')[0];\n    if (data[key]) {\n      data[key].count++;\n    }\n  });\n\n  renderGrid(data);\n}\n\nfunction getLevel(count) {\n  if (count === 0) return 'l0';\n  if (count <= 2) return 'l1';\n  if (count <= 5) return 'l2';\n  if (count <= 10) return 'l3';\n  return 'l4';\n}\n\nfunction renderGrid(data) {\n  var grid = qs('#grid');\n  grid.innerHTML = '';\n  \n  var keys = Object.keys(data).sort();\n  var tooltip = qs('#tooltip');\n  \n  // Calculate Streak\n  var streak = 0;\n  for(var i = keys.length - 1; i >= 0; i--) {\n      if(data[keys[i]].count > 0) streak++;\n      else if(keys[i] !== new Date().toISOString().split('T')[0]) break; // Allow today to be 0 without breaking streak yet\n  }\n  qs('#streak-val').textContent = streak;\n\n  keys.forEach(k => {\n    var item = data[k];\n    var sq = document.createElement('div');\n    sq.className = 'day-sq ' + getLevel(item.count);\n    \n    // Tooltip logic\n    sq.onmouseenter = (e) => {\n      tooltip.textContent = `${item.date.toLocaleDateString()} : ${item.count} edits`;\n      tooltip.style.opacity = 1;\n      var rect = sq.getBoundingClientRect();\n      var rootRect = root.getBoundingClientRect();\n      tooltip.style.left = (rect.left - rootRect.left + 5) + 'px';\n      tooltip.style.top = (rect.top - rootRect.top) + 'px';\n    };\n    sq.onmouseleave = () => tooltip.style.opacity = 0;\n    \n    grid.appendChild(sq);\n  });\n}\n\nfunction init() {\n  // Slight delay for Vault load\n  setTimeout(generateData, 200);\n  \n  // Refresh on modify\n  if(app && app.vault) {\n      app.vault.on('modify', () => setTimeout(generateData, 1000));\n  }\n}\n\ninit();",
    "tags": ["stats", "tracking", "gamification", "motivation", "github"]
  };