export default {
  "id": "yaml-api-test",
  "name": "YAML API Tester Pro",
  "description": "A powerful tool to test the new YAML API. Select any note from your vault and edit its YAML frontmatter (Properties) directly in JSON format. Perfect for advanced metadata management.",
  "author": "Infinition",
  "authorUrl": "https://github.com/infinition",
  "html": "<div class=\"test-container\">\n  <h4>🛠️ YAML API Tester Pro</h4>\n  \n  <div class=\"selector-row\">\n    <label>Target Note:</label>\n    <div class=\"search-wrapper\">\n      <input type=\"text\" id=\"note-search\" list=\"note-list\" placeholder=\"Search or select a note...\" onchange=\"handleTargetChange()\">\n      <datalist id=\"note-list\"></datalist>\n      <button onclick=\"refreshAll()\" class=\"mini-btn\">🔄</button>\n    </div>\n  </div>\n\n  <div class=\"editor-section\">\n    <label>YAML Properties (JSON):</label>\n    <textarea id=\"fm-editor\" placeholder=\"Loading frontmatter...\"></textarea>\n  </div>\n  \n  <div class=\"actions\">\n    <button onclick=\"saveYAML()\" class=\"save-btn\">💾 Save Properties</button>\n    <button onclick=\"refreshFM()\" class=\"secondary\">🔄 Refresh Editor</button>\n  </div>\n\n  <div class=\"quick-add\">\n    <label>Quick Add 'test_obsidget':</label>\n    <div class=\"search-wrapper\">\n      <input type=\"text\" id=\"prop-value\" placeholder=\"Enter value...\" oninput=\"saveLocalState()\">\n      <button onclick=\"addProperty()\">Add</button>\n    </div>\n  </div>\n\n  <div id=\"status-bar\" class=\"status\">Ready</div>\n</div>",
  "css": ".test-container {\n    background: var(--background-secondary);\n    border: 1px solid var(--background-modifier-border);\n    border-radius: 12px;\n    padding: 15px;\n    color: var(--text-normal);\n    box-sizing: border-box;\n    overflow: hidden;\n    min-width: 0;\n    max-width: 100%;\n}\n.selector-row, .editor-section, .quick-add {\n    margin-bottom: 12px;\n    display: flex;\n    flex-direction: column;\n    gap: 5px;\n    min-width: 0;\n}\nlabel {\n    font-size: 0.7rem;\n    font-weight: 700;\n    text-transform: uppercase;\n    color: var(--text-muted);\n}\n.search-wrapper {\n    display: flex;\n    gap: 8px;\n    width: 100%;\n    min-width: 0;\n}\n#note-search, #prop-value, #fm-editor {\n    width: 100%;\n    min-width: 0;\n    max-width: 100%;\n    box-sizing: border-box;\n    background: var(--background-primary);\n    color: var(--text-normal);\n    border: 1px solid var(--background-modifier-border);\n    border-radius: 6px;\n    padding: 8px;\n    font-size: 0.8rem;\n    outline: none;\n}\n#fm-editor {\n    height: 150px;\n    font-family: var(--font-monospace);\n    resize: vertical;\n    color: var(--text-accent);\n}\n#note-search:focus, #prop-value:focus, #fm-editor:focus {\n    border-color: var(--interactive-accent);\n    box-shadow: 0 0 0 2px rgba(var(--interactive-accent-rgb), 0.1);\n}\n.actions { display: flex; gap: 8px; margin-bottom: 15px; }\nbutton {\n    background: var(--interactive-accent);\n    color: var(--text-on-accent);\n    border: none;\n    padding: 6px 12px;\n    border-radius: 6px;\n    cursor: pointer;\n    font-size: 0.8rem;\n    font-weight: 600;\n}\nbutton.secondary {\n    background: var(--background-modifier-border);\n    color: var(--text-normal);\n}\nbutton.save-btn {\n    background: var(--background-modifier-success);\n    flex: 1;\n}\n.mini-btn {\n    padding: 8px;\n    background: var(--background-primary);\n    border: 1px solid var(--background-modifier-border);\n    border-radius: 6px;\n    cursor: pointer;\n}\n.status {\n    font-size: 0.65rem;\n    color: var(--text-muted);\n    margin-top: 10px;\n    font-style: italic;\n    border-top: 1px solid var(--background-modifier-border);\n    padding-top: 8px;\n}",
  "js": "async function saveLocalState() {\n    const path = root.getElementById('note-search').value;\n    const val = root.getElementById('prop-value').value;\n    await api.saveState({ targetPath: path, propValue: val });\n}\n\nasync function handleTargetChange() {\n    const path = root.getElementById('note-search').value;\n    if (!path || path.endsWith('.md') || path === \"\") {\n        await saveLocalState();\n        await refreshFM();\n    }\n}\n\nasync function refreshAll() {\n    await refreshNoteList();\n    await refreshFM();\n}\n\nasync function refreshFM() {\n    const editor = root.getElementById('fm-editor');\n    const path = root.getElementById('note-search').value;\n    \n    setStatus(\"Loading properties...\");\n    const fm = await api.getFrontmatter(path);\n    editor.value = JSON.stringify(fm, null, 2);\n    setStatus(\"Properties loaded\");\n}\n\nasync function saveYAML() {\n    const path = root.getElementById('note-search').value;\n    const content = root.getElementById('fm-editor').value;\n    \n    try {\n        const data = JSON.parse(content);\n        setStatus(\"Saving to YAML...\");\n        await api.updateFrontmatter(data, path);\n        new Notice(\"YAML properties updated!\");\n        setStatus(\"Saved successfully\");\n        refreshFM();\n    } catch (e) {\n        new Notice(\"Error: Invalid JSON format\");\n        setStatus(\"Error: Invalid JSON\");\n    }\n}\n\nasync function addProperty() {\n    const path = root.getElementById('note-search').value;\n    const val = root.getElementById('prop-value').value || (\"Test \" + Math.floor(Math.random() * 100));\n    \n    setStatus(\"Updating...\");\n    await api.updateFrontmatter({ \n        test_obsidget: val,\n        last_update: new Date().toLocaleTimeString()\n    }, path);\n    \n    new Notice(\"Property added!\");\n    refreshFM();\n}\n\nasync function refreshNoteList() {\n    const datalist = root.getElementById('note-list');\n    const files = await api.getFiles('md');\n    \n    datalist.innerHTML = '<option value=\"\">Current Note</option>';\n    files.forEach(file => {\n        const option = document.createElement('option');\n        option.value = file;\n        datalist.appendChild(option);\n    });\n    setStatus(\"Note list updated (\" + files.length + \" notes)\");\n}\n\nfunction setStatus(msg) {\n    root.getElementById('status-bar').innerText = msg;\n}\n\nasync function init() {\n    await refreshNoteList();\n    const saved = await api.getState();\n    if (saved) {\n        if (saved.targetPath) root.getElementById('note-search').value = saved.targetPath;\n        if (saved.propValue) root.getElementById('prop-value').value = saved.propValue;\n    }\n    await refreshFM();\n}\n\ninit();",
  "tags": [
    "test",
    "api",
    "yaml",
    "properties",
    "editor"
  ],
  "lastModifiedDate": 1769807048943,
  "createdDate": 1769807048943
};
